export const DATES_SELECT_DAY = 'DATES_SELECT_DAY';
export const DATES_CHANGE_DAYS_PER_YEAR = 'DATES_CHANGE_DAYS_PER_YEAR';
export const DATES_SELECT_START_MONTH = 'DATES_SELECT_START_MONTH';
export const DATES_SELECT_HOLIDAY = 'DATES_SELECT_HOLIDAY';
export const DATES_SELECT_END_OF_CURRENT = 'DATES_SELECT_END_OF_CURRENT';
export const DATES_CHANGE_YEAR = 'DATES_CHANGE_YEAR';
export const DATES_DESELECT = 'DATES_DESELECT';
export const DATES_UPDATE_CARRIED_OVER = 'DATES_UPDATE_CARRIED_OVER';
