export const DATES_SELECT_DAY = 'DATES_SELECT_DAY';
export const DATES_CHANGE_DAYS_PER_YEAR = 'DATES_CHANGE_DAYS_PER_YEAR';
export const DATES_CHANGE_STARTMONTH = 'DATES_CHANGE_STARTMONTH';
export const DATES_SELECT_HOLIDAY = 'DATES_SELECT_HOLIDAY';
export const DATES_CHANGE_YEAR = 'DATES_CHANGE_YEAR';
export const DATES_DESELECT = 'DATES_DESELECT';
