java -jar compiler.jar \
	--js logging.js \
	--js calendar-data.js \
	--js dropbox-functions.js \
	--js calendar-UI.js \
	--js calendar-dates.js \
	--js calendar-functions.js \
	--js calendar-social.js \
	--js calendar-start.js \
	--js analytics.js \
	--formatting pretty_print \
	--js_output_file ../js/trackmyholidays.js